"""Initial greenfield PowerMeter V2 schema.

Revision ID: 20260813_0001
Revises: None
Create Date: 2026-08-13

This revision is deliberately frozen. It must never import application ORM
metadata because later model changes cannot be allowed to rewrite history.
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "20260813_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backup_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("encrypted_path", sa.String(length=500), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("manifest_path", sa.String(length=500), nullable=True),
        sa.Column("byte_count", sa.BigInteger(), nullable=True),
        sa.Column("verification_evidence", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backup_runs")),
    )
    op.create_table(
        "calculation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("input_first_sequence", sa.BigInteger(), nullable=True),
        sa.Column("input_last_sequence", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculation_runs")),
    )
    op.create_table(
        "firmware_releases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("semantic_version", sa.String(length=40), nullable=False),
        sa.Column("build_number", sa.String(length=80), nullable=False),
        sa.Column("project_name", sa.String(length=80), nullable=False),
        sa.Column("target_chip", sa.String(length=40), nullable=False),
        sa.Column("board_profile", sa.String(length=80), nullable=False),
        sa.Column("minimum_protocol", sa.String(length=40), nullable=False),
        sa.Column("minimum_config_version", sa.Integer(), nullable=False),
        sa.Column("image_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("image_path", sa.String(length=500), nullable=False),
        sa.Column("release_notes", sa.Text(), nullable=False),
        sa.Column("manifest_signature", sa.String(length=256), nullable=False),
        sa.Column("candidate", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_releases")),
        sa.UniqueConstraint("semantic_version", name=op.f("uq_firmware_releases_semantic_version")),
        sa.UniqueConstraint("sha256", name=op.f("uq_firmware_releases_sha256")),
    )
    op.create_table(
        "homes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_homes")),
    )
    op.create_table(
        "permissions",
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_permissions")),
    )
    op.create_table(
        "rate_plans",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("utility_name", sa.String(length=120), nullable=False),
        sa.Column("rate_class", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_plans")),
    )
    op.create_table(
        "rate_sources",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("https_url", sa.String(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("check_interval_hours", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_sources")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("name", name=op.f("uq_roles_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "application_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_code", sa.String(length=100), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("correlation_id", sa.String(length=80), nullable=True),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("command_id", sa.String(length=36), nullable=True),
        sa.Column("sync_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_logs")),
    )
    op.create_index(
        op.f("ix_application_logs_command_id"), "application_logs", ["command_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_logs_correlation_id"),
        "application_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_logs_created_at"), "application_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_application_logs_device_id"), "application_logs", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_logs_event_code"), "application_logs", ["event_code"], unique=False
    )
    op.create_index(
        op.f("ix_application_logs_sync_id"), "application_logs", ["sync_id"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("event_code", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=80), nullable=True),
        sa.Column("target_id", sa.String(length=80), nullable=True),
        sa.Column("correlation_id", sa.String(length=80), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"), "audit_events", ["correlation_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_code"), "audit_events", ["event_code"], unique=False
    )
    op.create_table(
        "circuits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("aggregate_mode", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "aggregate_mode IN ('individual','verified_sum','parent_only')",
            name=op.f("ck_circuits_aggregate_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["home_id"], ["homes.id"], name=op.f("fk_circuits_home_id_homes"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["circuits.id"],
            name=op.f("fk_circuits_parent_id_circuits"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_circuits")),
    )
    op.create_index(op.f("ix_circuits_home_id"), "circuits", ["home_id"], unique=False)
    op.create_table(
        "mfa_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("enabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_counter", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_mfa_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mfa_credentials")),
        sa.UniqueConstraint("user_id", name=op.f("uq_mfa_credentials_user_id")),
    )
    op.create_table(
        "notification_settings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("minimum_severity", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_settings_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_settings")),
        sa.UniqueConstraint("user_id", "alert_type", name=op.f("uq_notification_settings_user_id")),
    )
    op.create_table(
        "rate_plan_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rate_plan_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("pricing_model", sa.String(length=40), nullable=False),
        sa.Column("daily_fixed_charge", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("monthly_fixed_charge", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("baseline_credit_per_kwh", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("cca_adjustment_per_kwh", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("surcharge_percent", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("published_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_rate_plan_versions_published_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["rate_plan_id"],
            ["rate_plans.id"],
            name=op.f("fk_rate_plan_versions_rate_plan_id_rate_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_plan_versions")),
        sa.UniqueConstraint(
            "rate_plan_id", "version", name=op.f("uq_rate_plan_versions_rate_plan_id")
        ),
    )
    op.create_index(
        op.f("ix_rate_plan_versions_rate_plan_id"),
        "rate_plan_versions",
        ["rate_plan_id"],
        unique=False,
    )
    op.create_table(
        "rate_source_revisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("etag", sa.String(length=300), nullable=True),
        sa.Column("last_modified", sa.String(length=200), nullable=True),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["rate_sources.id"],
            name=op.f("fk_rate_source_revisions_source_id_rate_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_source_revisions")),
        sa.UniqueConstraint(
            "source_id", "artifact_sha256", name=op.f("uq_rate_source_revisions_source_id")
        ),
    )
    op.create_index(
        op.f("ix_rate_source_revisions_source_id"),
        "rate_source_revisions",
        ["source_id"],
        unique=False,
    )
    op.create_table(
        "restore_tests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("backup_run_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("isolated_database_version", sa.String(length=80), nullable=True),
        sa.Column("migration_revision", sa.String(length=80), nullable=True),
        sa.Column("row_count_evidence", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["backup_run_id"],
            ["backup_runs.id"],
            name=op.f("fk_restore_tests_backup_run_id_backup_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_restore_tests")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("permission_name", sa.String(length=80), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_name"],
            ["permissions.name"],
            name=op.f("fk_role_permissions_permission_name_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_name", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("client_fingerprint", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_home_scopes",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["homes.id"],
            name=op.f("fk_user_home_scopes_home_id_homes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_home_scopes_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "home_id", name=op.f("pk_user_home_scopes")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "utility_accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("utility_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("billing_day", sa.Integer(), nullable=False),
        sa.Column("cost_scope", sa.String(length=32), nullable=False),
        sa.Column("baseline_allocation_kwh", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("cca_provider", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "cost_scope IN ('energy_only','allocated_account','full_account')",
            name=op.f("ck_utility_accounts_cost_scope"),
        ),
        sa.CheckConstraint(
            "billing_day >= 1 AND billing_day <= 28", name=op.f("ck_utility_accounts_billing_day")
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["homes.id"],
            name=op.f("fk_utility_accounts_home_id_homes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_accounts")),
        sa.UniqueConstraint("home_id", name=op.f("uq_utility_accounts_home_id")),
    )
    op.create_table(
        "utility_bill_rate_uploads",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.Column("encrypted_artifact_path", sa.String(length=500), nullable=True),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=80), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("uploaded_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("artifact_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_utility_bill_rate_uploads_uploaded_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_bill_rate_uploads")),
        sa.UniqueConstraint("artifact_sha256", name="uq_utility_bill_rate_uploads_artifact_sha256"),
    )
    op.create_table(
        "billing_cycles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("utility_account_id", sa.String(length=36), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.ForeignKeyConstraint(
            ["utility_account_id"],
            ["utility_accounts.id"],
            name=op.f("fk_billing_cycles_utility_account_id_utility_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_cycles")),
        sa.UniqueConstraint(
            "utility_account_id", "start_date", name=op.f("uq_billing_cycles_utility_account_id")
        ),
    )
    op.create_index(
        op.f("ix_billing_cycles_utility_account_id"),
        "billing_cycles",
        ["utility_account_id"],
        unique=False,
    )
    op.create_table(
        "cost_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rate_plan_version_id", sa.String(length=36), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("interval_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cost_scope", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["rate_plan_version_id"],
            ["rate_plan_versions.id"],
            name=op.f("fk_cost_runs_rate_plan_version_id_rate_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cost_runs")),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("circuit_id", sa.String(length=36), nullable=True),
        sa.Column("friendly_name", sa.String(length=120), nullable=False),
        sa.Column("protocol_id", sa.String(length=40), nullable=False),
        sa.Column("pzem_variant", sa.String(length=80), nullable=False),
        sa.Column("ct_rating_a", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("measurement_scope", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("firmware_version", sa.String(length=80), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contiguous_ack", sa.BigInteger(), nullable=False),
        sa.Column("maximum_sequence", sa.BigInteger(), nullable=False),
        sa.Column("reset_generation", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "measurement_scope IN ('energy_only','allocated_account','full_account')",
            name=op.f("ck_devices_measurement_scope"),
        ),
        sa.CheckConstraint(
            "contiguous_ack >= 0 AND maximum_sequence >= 0",
            name=op.f("ck_devices_sequence_nonnegative"),
        ),
        sa.CheckConstraint(
            "ct_rating_a > 0 AND ct_rating_a <= 1000", name=op.f("ck_devices_ct_rating")
        ),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.id"],
            name=op.f("fk_devices_circuit_id_circuits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["home_id"], ["homes.id"], name=op.f("fk_devices_home_id_homes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
    )
    op.create_index(op.f("ix_devices_home_id"), "devices", ["home_id"], unique=False)
    op.create_index(
        op.f("ix_devices_last_heartbeat_at"), "devices", ["last_heartbeat_at"], unique=False
    )
    op.create_table(
        "rate_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("utility_account_id", sa.String(length=36), nullable=False),
        sa.Column("rate_plan_version_id", sa.String(length=36), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by_user_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by_user_id"],
            ["users.id"],
            name=op.f("fk_rate_assignments_assigned_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_plan_version_id"],
            ["rate_plan_versions.id"],
            name=op.f("fk_rate_assignments_rate_plan_version_id_rate_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["utility_account_id"],
            ["utility_accounts.id"],
            name=op.f("fk_rate_assignments_utility_account_id_utility_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_assignments")),
    )
    op.create_index(
        op.f("ix_rate_assignments_utility_account_id"),
        "rate_assignments",
        ["utility_account_id"],
        unique=False,
    )
    op.create_table(
        "rate_candidates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_revision_id", sa.String(length=36), nullable=False),
        sa.Column("normalized_rates", sa.JSON(), nullable=False),
        sa.Column("diff", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_rate_candidates_reviewed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["source_revision_id"],
            ["rate_source_revisions.id"],
            name=op.f("fk_rate_candidates_source_revision_id_rate_source_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_candidates")),
    )
    op.create_table(
        "rate_periods",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("rate_plan_version_id", sa.String(length=36), nullable=False),
        sa.Column("season", sa.String(length=30), nullable=False),
        sa.Column("day_type", sa.String(length=30), nullable=False),
        sa.Column("period_name", sa.String(length=40), nullable=False),
        sa.Column("start_minute", sa.Integer(), nullable=False),
        sa.Column("end_minute", sa.Integer(), nullable=False),
        sa.Column("price_per_kwh", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("delivery_per_kwh", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("generation_per_kwh", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("tier_start_kwh", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("tier_end_kwh", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.CheckConstraint(
            "end_minute > 0 AND end_minute <= 1440", name=op.f("ck_rate_periods_end_minute")
        ),
        sa.CheckConstraint("end_minute > start_minute", name=op.f("ck_rate_periods_period_order")),
        sa.CheckConstraint(
            "start_minute >= 0 AND start_minute < 1440", name=op.f("ck_rate_periods_start_minute")
        ),
        sa.ForeignKeyConstraint(
            ["rate_plan_version_id"],
            ["rate_plan_versions.id"],
            name=op.f("fk_rate_periods_rate_plan_version_id_rate_plan_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_periods")),
    )
    op.create_index(
        op.f("ix_rate_periods_rate_plan_version_id"),
        "rate_periods",
        ["rate_plan_version_id"],
        unique=False,
    )
    op.create_table(
        "rate_source_artifacts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("revision_id", sa.String(length=36), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("byte_count", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["rate_source_revisions.id"],
            name=op.f("fk_rate_source_artifacts_revision_id_rate_source_revisions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_source_artifacts")),
    )
    op.create_table(
        "rate_sync_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("event_code", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revision_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["rate_source_revisions.id"],
            name=op.f("fk_rate_sync_runs_revision_id_rate_source_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["rate_sources.id"],
            name=op.f("fk_rate_sync_runs_source_id_rate_sources"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rate_sync_runs")),
    )
    op.create_table(
        "utility_bill_rate_extractions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("upload_id", sa.String(length=36), nullable=False),
        sa.Column("utility_name", sa.String(length=120), nullable=False),
        sa.Column("rate_plan_name", sa.String(length=120), nullable=False),
        sa.Column("rate_class", sa.String(length=80), nullable=False),
        sa.Column("cca_or_direct_access_indicator", sa.String(length=80), nullable=True),
        sa.Column("season_definitions", sa.JSON(), nullable=False),
        sa.Column("day_type_definitions", sa.JSON(), nullable=False),
        sa.Column("tou_period_definitions", sa.JSON(), nullable=False),
        sa.Column("tier_threshold_definitions", sa.JSON(), nullable=False),
        sa.Column("reusable_price_components", sa.JSON(), nullable=False),
        sa.Column("baseline_allocation_rule", sa.String(length=500), nullable=True),
        sa.Column("baseline_credit_rate", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("effective_start_candidate", sa.Date(), nullable=True),
        sa.Column("effective_end_candidate", sa.Date(), nullable=True),
        sa.Column("source_evidence", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("reviewer_user_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resulting_rate_version_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["resulting_rate_version_id"],
            ["rate_plan_versions.id"],
            name=op.f(
                "fk_utility_bill_rate_extractions_resulting_rate_version_id_rate_plan_versions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_user_id"],
            ["users.id"],
            name=op.f("fk_utility_bill_rate_extractions_reviewer_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["utility_bill_rate_uploads.id"],
            name=op.f("fk_utility_bill_rate_extractions_upload_id_utility_bill_rate_uploads"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_bill_rate_extractions")),
        sa.UniqueConstraint("upload_id", name=op.f("uq_utility_bill_rate_extractions_upload_id")),
    )
    op.create_table(
        "alert_condition_states",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope_key", sa.String(length=180), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("last_observation_key", sa.String(length=180), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alert_condition_states_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["homes.id"],
            name=op.f("fk_alert_condition_states_home_id_homes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_condition_states")),
        sa.UniqueConstraint("scope_key", name=op.f("uq_alert_condition_states_scope_key")),
    )
    op.create_index(
        op.f("ix_alert_condition_states_device_id"),
        "alert_condition_states",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_condition_states_home_id"),
        "alert_condition_states",
        ["home_id"],
        unique=False,
    )
    op.create_table(
        "alert_maintenance_windows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("alert_type", sa.String(length=80), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_by_user_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "ends_at > starts_at", name=op.f("ck_alert_maintenance_windows_ordered_window")
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_user_id"],
            ["users.id"],
            name=op.f("fk_alert_maintenance_windows_cancelled_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_alert_maintenance_windows_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alert_maintenance_windows_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["homes.id"],
            name=op.f("fk_alert_maintenance_windows_home_id_homes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_maintenance_windows")),
    )
    op.create_index(
        op.f("ix_alert_maintenance_windows_device_id"),
        "alert_maintenance_windows",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_alert_maintenance_windows_home_id"),
        "alert_maintenance_windows",
        ["home_id"],
        unique=False,
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=True),
        sa.Column("alert_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("silenced_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_alerts_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["home_id"], ["homes.id"], name=op.f("fk_alerts_home_id_homes"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index(op.f("ix_alerts_home_id"), "alerts", ["home_id"], unique=False)
    op.create_table(
        "billing_estimates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("utility_account_id", sa.String(length=36), nullable=False),
        sa.Column("cost_run_id", sa.String(length=36), nullable=False),
        sa.Column("scope_start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scope_end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensor_energy_mwh", sa.BigInteger(), nullable=False),
        sa.Column("total_microdollars", sa.BigInteger(), nullable=False),
        sa.Column("completeness", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("missing_intervals", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_run_id"],
            ["cost_runs.id"],
            name=op.f("fk_billing_estimates_cost_run_id_cost_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["utility_account_id"],
            ["utility_accounts.id"],
            name=op.f("fk_billing_estimates_utility_account_id_utility_accounts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_estimates")),
    )
    op.create_table(
        "device_capabilities",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_capabilities_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_capabilities")),
        sa.UniqueConstraint("device_id", "name", name=op.f("uq_device_capabilities_device_id")),
    )
    op.create_index(
        op.f("ix_device_capabilities_device_id"), "device_capabilities", ["device_id"], unique=False
    )
    op.create_table(
        "device_commands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("command_type", sa.String(length=60), nullable=False),
        sa.Column("issued_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("not_before", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("required_firmware_capability", sa.String(length=100), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("last_result", sa.JSON(), nullable=True),
        sa.Column("created_audit_id", sa.String(length=36), nullable=False),
        sa.Column("prepare_token_hash", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "progress_percent >= 0 AND progress_percent <= 100",
            name=op.f("ck_device_commands_progress"),
        ),
        sa.ForeignKeyConstraint(
            ["created_audit_id"],
            ["audit_events.id"],
            name=op.f("fk_device_commands_created_audit_id_audit_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_commands_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_device_commands_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_commands")),
        sa.UniqueConstraint(
            "device_id", "idempotency_key", name=op.f("uq_device_commands_device_id")
        ),
    )
    op.create_index(
        op.f("ix_device_commands_device_id"), "device_commands", ["device_id"], unique=False
    )
    op.create_table(
        "device_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=True),
        sa.Column("event_code", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_events_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_events")),
    )
    op.create_index(
        op.f("ix_device_events_device_id"), "device_events", ["device_id"], unique=False
    )
    op.create_table(
        "device_heartbeats",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("boot_id", sa.String(length=36), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("voltage_v", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("current_a", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("active_power_w", sa.Numeric(precision=14, scale=3), nullable=True),
        sa.Column("frequency_hz", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("power_factor", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("pzem_status", sa.String(length=40), nullable=False),
        sa.Column("storage_status", sa.String(length=40), nullable=False),
        sa.Column("time_status", sa.String(length=40), nullable=False),
        sa.Column("wifi_rssi", sa.Integer(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("backlog", sa.BigInteger(), nullable=False),
        sa.Column("oldest_sequence", sa.BigInteger(), nullable=True),
        sa.Column("newest_sequence", sa.BigInteger(), nullable=True),
        sa.Column("free_internal_heap", sa.BigInteger(), nullable=True),
        sa.Column("largest_internal_block", sa.BigInteger(), nullable=True),
        sa.Column("reboot_reason", sa.String(length=80), nullable=True),
        sa.Column("health_flags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_heartbeats_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_heartbeats")),
    )
    op.create_index(
        op.f("ix_device_heartbeats_device_id"), "device_heartbeats", ["device_id"], unique=False
    )
    op.create_index(
        op.f("ix_device_heartbeats_received_at"), "device_heartbeats", ["received_at"], unique=False
    )
    op.create_table(
        "device_nonces",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("nonce_hash", sa.String(length=64), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_nonces_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_nonces")),
        sa.UniqueConstraint("device_id", "nonce_hash", name=op.f("uq_device_nonces_device_id")),
    )
    op.create_index(
        op.f("ix_device_nonces_device_id"), "device_nonces", ["device_id"], unique=False
    )
    op.create_index(op.f("ix_device_nonces_seen_at"), "device_nonces", ["seen_at"], unique=False)
    op.create_table(
        "enrollment_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("home_id", sa.String(length=36), nullable=False),
        sa.Column("friendly_name", sa.String(length=120), nullable=False),
        sa.Column("ct_rating_a", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("pzem_variant", sa.String(length=80), nullable=False),
        sa.Column("issued_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_by_device_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["consumed_by_device_id"],
            ["devices.id"],
            name=op.f("fk_enrollment_tokens_consumed_by_device_id_devices"),
        ),
        sa.ForeignKeyConstraint(
            ["home_id"],
            ["homes.id"],
            name=op.f("fk_enrollment_tokens_home_id_homes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["issued_by_user_id"],
            ["users.id"],
            name=op.f("fk_enrollment_tokens_issued_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_enrollment_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_enrollment_tokens_home_id"), "enrollment_tokens", ["home_id"], unique=False
    )
    op.create_table(
        "firmware_deployments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("firmware_release_id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("progress_percent", sa.Integer(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_firmware_deployments_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["firmware_release_id"],
            ["firmware_releases.id"],
            name=op.f("fk_firmware_deployments_firmware_release_id_firmware_releases"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_firmware_deployments")),
    )
    op.create_index(
        op.f("ix_firmware_deployments_device_id"),
        "firmware_deployments",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "raw_readings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("reset_generation", sa.Integer(), nullable=False),
        sa.Column("interval_start_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interval_end_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("monotonic_start_us", sa.BigInteger(), nullable=False),
        sa.Column("monotonic_end_us", sa.BigInteger(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=False),
        sa.Column("expected_sample_count", sa.Integer(), nullable=False),
        sa.Column("voltage_mv", sa.BigInteger(), nullable=True),
        sa.Column("current_ma", sa.BigInteger(), nullable=True),
        sa.Column("active_power_mw", sa.BigInteger(), nullable=True),
        sa.Column("frequency_mhz", sa.BigInteger(), nullable=True),
        sa.Column("power_factor_milli", sa.Integer(), nullable=True),
        sa.Column("pzem_energy_wh", sa.BigInteger(), nullable=True),
        sa.Column("interval_energy_mwh", sa.BigInteger(), nullable=True),
        sa.Column("energy_selection", sa.String(length=40), nullable=False),
        sa.Column("pzem_status", sa.String(length=40), nullable=False),
        sa.Column("time_trusted", sa.Boolean(), nullable=False),
        sa.Column("flags", sa.JSON(), nullable=False),
        sa.Column("record_crc32", sa.BigInteger(), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "interval_energy_mwh IS NULL OR interval_energy_mwh >= 0",
            name=op.f("ck_raw_readings_energy_nonnegative"),
        ),
        sa.CheckConstraint(
            "sample_count >= 0 AND expected_sample_count > 0",
            name=op.f("ck_raw_readings_sample_count"),
        ),
        sa.CheckConstraint("sequence > 0", name=op.f("ck_raw_readings_sequence_positive")),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_raw_readings_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_readings")),
        sa.UniqueConstraint("device_id", "sequence", name=op.f("uq_raw_readings_device_id")),
    )
    op.create_index(op.f("ix_raw_readings_device_id"), "raw_readings", ["device_id"], unique=False)
    op.create_index(
        "ix_raw_readings_device_time",
        "raw_readings",
        ["device_id", "interval_start_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_raw_readings_interval_end_utc"), "raw_readings", ["interval_end_utc"], unique=False
    )
    op.create_index(
        op.f("ix_raw_readings_interval_start_utc"),
        "raw_readings",
        ["interval_start_utc"],
        unique=False,
    )
    op.create_table(
        "rollups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("bucket", sa.String(length=20), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("energy_mwh", sa.BigInteger(), nullable=False),
        sa.Column("completeness", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("interval_count", sa.Integer(), nullable=False),
        sa.Column("calculation_run_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["calculation_run_id"],
            ["calculation_runs.id"],
            name=op.f("fk_rollups_calculation_run_id_calculation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_rollups_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rollups")),
        sa.UniqueConstraint("device_id", "bucket", "start_utc", name=op.f("uq_rollups_device_id")),
    )
    op.create_index(op.f("ix_rollups_device_id"), "rollups", ["device_id"], unique=False)
    op.create_index(op.f("ix_rollups_start_utc"), "rollups", ["start_utc"], unique=False)
    op.create_table(
        "unavailable_sequence_ranges",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("first_sequence", sa.BigInteger(), nullable=False),
        sa.Column("last_sequence", sa.BigInteger(), nullable=False),
        sa.Column("reason_code", sa.String(length=80), nullable=False),
        sa.Column("evidence_sha256", sa.String(length=64), nullable=False),
        sa.Column("authenticated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "first_sequence > 0 AND last_sequence >= first_sequence",
            name=op.f("ck_unavailable_sequence_ranges_ordered_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_unavailable_sequence_ranges_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unavailable_sequence_ranges")),
        sa.UniqueConstraint(
            "device_id",
            "first_sequence",
            "last_sequence",
            name=op.f("uq_unavailable_sequence_ranges_device_id"),
        ),
    )
    op.create_index(
        op.f("ix_unavailable_sequence_ranges_device_id"),
        "unavailable_sequence_ranges",
        ["device_id"],
        unique=False,
    )
    op.create_table(
        "utility_bill_rate_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("extraction_id", sa.String(length=36), nullable=False),
        sa.Column("allowed_field", sa.String(length=100), nullable=False),
        sa.Column("prior_value_hash", sa.String(length=64), nullable=False),
        sa.Column("corrected_value", sa.Text(), nullable=False),
        sa.Column("corrected_by_user_id", sa.String(length=36), nullable=False),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["corrected_by_user_id"],
            ["users.id"],
            name=op.f("fk_utility_bill_rate_corrections_corrected_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["extraction_id"],
            ["utility_bill_rate_extractions.id"],
            name=op.f(
                "fk_utility_bill_rate_corrections_extraction_id_utility_bill_rate_extractions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_utility_bill_rate_corrections")),
    )
    op.create_index(
        op.f("ix_utility_bill_rate_corrections_extraction_id"),
        "utility_bill_rate_corrections",
        ["extraction_id"],
        unique=False,
    )
    op.create_table(
        "alert_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("alert_id", sa.String(length=36), nullable=False),
        sa.Column("event_code", sa.String(length=80), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alerts.id"],
            name=op.f("fk_alert_events_alert_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    op.create_index(op.f("ix_alert_events_alert_id"), "alert_events", ["alert_id"], unique=False)
    op.create_table(
        "device_command_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("command_id", sa.String(length=36), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("result_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("result_code", sa.String(length=80), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["device_commands.id"],
            name=op.f("fk_device_command_attempts_command_id_device_commands"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_command_attempts")),
        sa.UniqueConstraint(
            "command_id", "attempt", name=op.f("uq_device_command_attempts_command_id")
        ),
    )
    op.create_index(
        op.f("ix_device_command_attempts_command_id"),
        "device_command_attempts",
        ["command_id"],
        unique=False,
    )
    op.create_table(
        "device_credentials",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("encrypted_secret", sa.LargeBinary(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_credentials_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_credentials")),
    )
    op.create_index(
        op.f("ix_device_credentials_device_id"), "device_credentials", ["device_id"], unique=False
    )
    op.create_table(
        "normalized_intervals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("device_id", sa.String(length=36), nullable=False),
        sa.Column("raw_reading_id", sa.String(length=36), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("energy_mwh", sa.BigInteger(), nullable=False),
        sa.Column("average_power_mw", sa.BigInteger(), nullable=True),
        sa.Column("completeness", sa.Numeric(precision=7, scale=6), nullable=False),
        sa.Column("energy_selection", sa.String(length=40), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("source_authenticated", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "completeness >= 0 AND completeness <= 1",
            name=op.f("ck_normalized_intervals_completeness"),
        ),
        sa.CheckConstraint("end_utc > start_utc", name=op.f("ck_normalized_intervals_time_order")),
        sa.CheckConstraint(
            "energy_mwh >= 0", name=op.f("ck_normalized_intervals_energy_nonnegative")
        ),
        sa.CheckConstraint(
            "source_authenticated = true", name=op.f("ck_normalized_intervals_authenticated_source")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_normalized_intervals_device_id_devices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["raw_reading_id"],
            ["raw_readings.id"],
            name=op.f("fk_normalized_intervals_raw_reading_id_raw_readings"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_normalized_intervals")),
        sa.UniqueConstraint("raw_reading_id", name=op.f("uq_normalized_intervals_raw_reading_id")),
    )
    op.create_index(
        op.f("ix_normalized_intervals_device_id"),
        "normalized_intervals",
        ["device_id"],
        unique=False,
    )
    op.create_index(
        "ix_normalized_intervals_device_time",
        "normalized_intervals",
        ["device_id", "start_utc"],
        unique=False,
    )
    op.create_index(
        op.f("ix_normalized_intervals_end_utc"), "normalized_intervals", ["end_utc"], unique=False
    )
    op.create_index(
        op.f("ix_normalized_intervals_start_utc"),
        "normalized_intervals",
        ["start_utc"],
        unique=False,
    )
    op.create_table(
        "interval_costs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("normalized_interval_id", sa.String(length=36), nullable=False),
        sa.Column("cost_run_id", sa.String(length=36), nullable=False),
        sa.Column("rate_plan_version_id", sa.String(length=36), nullable=False),
        sa.Column("energy_mwh", sa.BigInteger(), nullable=False),
        sa.Column("energy_cost_microdollars", sa.BigInteger(), nullable=False),
        sa.Column("credit_microdollars", sa.BigInteger(), nullable=False),
        sa.Column("period_name", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["cost_run_id"],
            ["cost_runs.id"],
            name=op.f("fk_interval_costs_cost_run_id_cost_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["normalized_interval_id"],
            ["normalized_intervals.id"],
            name=op.f("fk_interval_costs_normalized_interval_id_normalized_intervals"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["rate_plan_version_id"],
            ["rate_plan_versions.id"],
            name=op.f("fk_interval_costs_rate_plan_version_id_rate_plan_versions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interval_costs")),
        sa.UniqueConstraint(
            "normalized_interval_id",
            "cost_run_id",
            name=op.f("uq_interval_costs_normalized_interval_id"),
        ),
    )
    op.create_index(
        op.f("ix_interval_costs_normalized_interval_id"),
        "interval_costs",
        ["normalized_interval_id"],
        unique=False,
    )
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION pm_reject_immutable_change() RETURNS trigger AS $$
            BEGIN
              RAISE EXCEPTION 'immutable PowerMeter evidence cannot be changed';
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        for table in ("raw_readings", "audit_events", "interval_costs", "billing_estimates"):
            op.execute(
                f"CREATE TRIGGER {table}_immutable BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION pm_reject_immutable_change()"
            )
        op.execute(
            """
            CREATE OR REPLACE FUNCTION pm_reject_published_rate_change() RETURNS trigger AS $$
            BEGIN
              IF OLD.state = 'published' THEN
                RAISE EXCEPTION 'published rate version is immutable';
              END IF;
              RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        op.execute(
            "CREATE TRIGGER rate_plan_versions_immutable BEFORE UPDATE OR DELETE "
            "ON rate_plan_versions FOR EACH ROW "
            "EXECUTE FUNCTION pm_reject_published_rate_change()"
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interval_costs_normalized_interval_id"), table_name="interval_costs")
    op.drop_table("interval_costs")
    op.drop_index(op.f("ix_normalized_intervals_start_utc"), table_name="normalized_intervals")
    op.drop_index(op.f("ix_normalized_intervals_end_utc"), table_name="normalized_intervals")
    op.drop_index("ix_normalized_intervals_device_time", table_name="normalized_intervals")
    op.drop_index(op.f("ix_normalized_intervals_device_id"), table_name="normalized_intervals")
    op.drop_table("normalized_intervals")
    op.drop_index(op.f("ix_device_credentials_device_id"), table_name="device_credentials")
    op.drop_table("device_credentials")
    op.drop_index(
        op.f("ix_device_command_attempts_command_id"), table_name="device_command_attempts"
    )
    op.drop_table("device_command_attempts")
    op.drop_index(op.f("ix_alert_events_alert_id"), table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(
        op.f("ix_utility_bill_rate_corrections_extraction_id"),
        table_name="utility_bill_rate_corrections",
    )
    op.drop_table("utility_bill_rate_corrections")
    op.drop_index(
        op.f("ix_unavailable_sequence_ranges_device_id"), table_name="unavailable_sequence_ranges"
    )
    op.drop_table("unavailable_sequence_ranges")
    op.drop_index(op.f("ix_rollups_start_utc"), table_name="rollups")
    op.drop_index(op.f("ix_rollups_device_id"), table_name="rollups")
    op.drop_table("rollups")
    op.drop_index(op.f("ix_raw_readings_interval_start_utc"), table_name="raw_readings")
    op.drop_index(op.f("ix_raw_readings_interval_end_utc"), table_name="raw_readings")
    op.drop_index("ix_raw_readings_device_time", table_name="raw_readings")
    op.drop_index(op.f("ix_raw_readings_device_id"), table_name="raw_readings")
    op.drop_table("raw_readings")
    op.drop_index(op.f("ix_firmware_deployments_device_id"), table_name="firmware_deployments")
    op.drop_table("firmware_deployments")
    op.drop_index(op.f("ix_enrollment_tokens_home_id"), table_name="enrollment_tokens")
    op.drop_table("enrollment_tokens")
    op.drop_index(op.f("ix_device_nonces_seen_at"), table_name="device_nonces")
    op.drop_index(op.f("ix_device_nonces_device_id"), table_name="device_nonces")
    op.drop_table("device_nonces")
    op.drop_index(op.f("ix_device_heartbeats_received_at"), table_name="device_heartbeats")
    op.drop_index(op.f("ix_device_heartbeats_device_id"), table_name="device_heartbeats")
    op.drop_table("device_heartbeats")
    op.drop_index(op.f("ix_device_events_device_id"), table_name="device_events")
    op.drop_table("device_events")
    op.drop_index(op.f("ix_device_commands_device_id"), table_name="device_commands")
    op.drop_table("device_commands")
    op.drop_index(op.f("ix_device_capabilities_device_id"), table_name="device_capabilities")
    op.drop_table("device_capabilities")
    op.drop_table("billing_estimates")
    op.drop_index(op.f("ix_alerts_home_id"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(
        op.f("ix_alert_maintenance_windows_home_id"), table_name="alert_maintenance_windows"
    )
    op.drop_index(
        op.f("ix_alert_maintenance_windows_device_id"), table_name="alert_maintenance_windows"
    )
    op.drop_table("alert_maintenance_windows")
    op.drop_index(op.f("ix_alert_condition_states_home_id"), table_name="alert_condition_states")
    op.drop_index(op.f("ix_alert_condition_states_device_id"), table_name="alert_condition_states")
    op.drop_table("alert_condition_states")
    op.drop_table("utility_bill_rate_extractions")
    op.drop_table("rate_sync_runs")
    op.drop_table("rate_source_artifacts")
    op.drop_index(op.f("ix_rate_periods_rate_plan_version_id"), table_name="rate_periods")
    op.drop_table("rate_periods")
    op.drop_table("rate_candidates")
    op.drop_index(op.f("ix_rate_assignments_utility_account_id"), table_name="rate_assignments")
    op.drop_table("rate_assignments")
    op.drop_index(op.f("ix_devices_last_heartbeat_at"), table_name="devices")
    op.drop_index(op.f("ix_devices_home_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_table("cost_runs")
    op.drop_index(op.f("ix_billing_cycles_utility_account_id"), table_name="billing_cycles")
    op.drop_table("billing_cycles")
    op.drop_table("utility_bill_rate_uploads")
    op.drop_table("utility_accounts")
    op.drop_table("user_roles")
    op.drop_table("user_home_scopes")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("role_permissions")
    op.drop_table("restore_tests")
    op.drop_index(op.f("ix_rate_source_revisions_source_id"), table_name="rate_source_revisions")
    op.drop_table("rate_source_revisions")
    op.drop_index(op.f("ix_rate_plan_versions_rate_plan_id"), table_name="rate_plan_versions")
    op.drop_table("rate_plan_versions")
    op.drop_table("notification_settings")
    op.drop_table("mfa_credentials")
    op.drop_index(op.f("ix_circuits_home_id"), table_name="circuits")
    op.drop_table("circuits")
    op.drop_index(op.f("ix_audit_events_event_code"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_application_logs_sync_id"), table_name="application_logs")
    op.drop_index(op.f("ix_application_logs_event_code"), table_name="application_logs")
    op.drop_index(op.f("ix_application_logs_device_id"), table_name="application_logs")
    op.drop_index(op.f("ix_application_logs_created_at"), table_name="application_logs")
    op.drop_index(op.f("ix_application_logs_correlation_id"), table_name="application_logs")
    op.drop_index(op.f("ix_application_logs_command_id"), table_name="application_logs")
    op.drop_table("application_logs")
    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("rate_sources")
    op.drop_table("rate_plans")
    op.drop_table("permissions")
    op.drop_table("homes")
    op.drop_table("firmware_releases")
    op.drop_table("calculation_runs")
    op.drop_table("backup_runs")
